pipeline {  
    
    parameters {
        string(name: 'folderName', defaultValue: 'nuovaCartella', description: 'folder name to create or access to it')
        booleanParam(name: 'createFolder', defaultValue: false, description: 'true if the folder is not created yet')
        string(name: 'fileName', defaultValue: 'nuovoFile.txt', description: 'file name to create')
    }

    agent  any

    stages {
        stage('Upload file & Plan') {
            steps{
                script {
                    if (params.createFolder) {
                        echo 'create folder'
                        sh 'pwd;mkdir ${folderName}'
                    }
                    echo 'create file into folder'
                    sh 'pwd;chmod 755 ${folderName}'
                    sh 'pwd;cd ${folderName}'
                    node {
                        def fb64 = input message: 'upload', parameters: [base64File('file')]
                        def file_in_workspace = unstashParam $fb64
                        withEnv(["fb64=$fb64"]) {
                            sh 'pwd;cat >> ${fileName} ${file_in_workspace}'
                        }
                    }
                }
            }
        }
    }
}
