pipeline {  
    
    parameters {
        string(name: 'folderName', defaultValue: 'Nuova Cartella', description: 'folder name to create or access to it')
        booleanParam(name: 'createFolder', defaultValue: false, description: 'true if the folder is not created yet')
    }

    agent  any

    stages {
        stage('Upload file & Plan') {
            steps{
                script {
                    if (params.createFolder) {
                        echo 'create folder'
                        sh 'pwd;mkdir ${folderName}'
                    }
                    echo 'create file into folder'
                    sh 'pwd;cd ${folderName}'
                    node {
                        def fb64 = input message: 'upload', parameters: [base64File('file')]
                        withEnv(["fb64=$fb64"]) {
                            sh 'pwd;touch nuovoFile.txt'
                            sh 'pwd;cp $fb64 nuovoFile.txt'
                        }
                    }
                }
            }
        }
    }
}
